network:
  version: 2
  ethernets:
    ens33:
      addresses:
        - 192.168.1.11/24
      gateway4: 
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
